import type { Metadata } from 'next'
import { AntdRegistry } from '@ant-design/nextjs-registry' // 解决 antd 闪烁问题

// google 字体
import {
  // Inter,
  // Tajawal,
  // Dosis,
  // Noto_Sans,
  // Comforter,
  // Roboto,
  // EB_Garamond
  // Poppins,
  Lora
  // Alegreya,
  // Libre_Baskerville,
  // Rufina,
  // Playfair_Display,
  // Lato
} from 'next/font/google'
import './globals.css'

const fontStyleSetting = Lora({
  // variable: '--font-inter-sans',
  subsets: ['latin'],
  display: 'swap',
  weight: '400'
})

export const metadata: Metadata = {
  title: 'My Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode
  modal: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${fontStyleSetting.className} antialiased`}>
        <AntdRegistry>
          {children}
          {modal}
        </AntdRegistry>
      </body>
    </html>
  )
}
