import type { Metadata } from 'next'
import { AntdRegistry } from '@ant-design/nextjs-registry' // 解决 antd 闪烁问题
import Link from 'next/link'
// google 字体
import {
  // Inter,
  // Tajawal,
  // Dosis,
  // Noto_Sans,
  // Comforter,
  // Roboto,
  // EB_Garamond
  // Poppins,
  Lora,
  // Alegreya,
  // Libre_Baskerville,
  // Rufina,
  // Playfair_Display,
  // Lato
} from 'next/font/google'
import './globals.css'

const fontStyleSetting = Lora({
  // variable: '--font-inter-sans',
  subsets: ['latin'],
  display: 'swap',
  weight: '400'
})

export const metadata: Metadata = {
  title: 'My Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  team,
  analytics
}: Readonly<{
  children: React.ReactNode
  team: React.ReactNode
  analytics: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${fontStyleSetting.className} antialiased`}>
        <AntdRegistry>
          <div className='container mx-auto'>
            <div className='flex justify-center text-blue-600 p-6 gap-6'>
              <Link href='/'>Home</Link>
              <Link href='/visitors'>Visitors</Link>
            </div>
            <div className='flex gap-6 p-6'>
              {team}
              {analytics}
            </div>
            {children}
          </div>
        </AntdRegistry>
      </body>
    </html>
  )
}
